[added] ExternalStream to StreamSourceInfo and updated server
nats-io/jsm.go pull request #247
Opened 2021-05-13 20:26 UTC by matthiashanel

Instead of adding the field the server struct itself is used.

Signed-off-by: Matthias Hanel <mh@synadia.com>

Reflecting this [change](https://github.com/nats-io/nats-server/commit/060f2ec127d231d098c171e7d180925b336d5382) in jsml.

2021-05-13 20:28 UTC, ripienaar requested changes
Please add locally.

2021-05-13 20:38 UTC, matthiashanel commented
Added locally instead

2021-05-14 10:36 UTC, ripienaar commented on api/streams.go
> +	External *ExternalStream `json:"external,omitempty"`
We need to add this to the schemas as well

2021-05-14 17:45 UTC, ripienaar commented
LGTM

2021-05-14 17:59 UTC, merged